name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - Rivarsal
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    id: jmx
    attributes:
      label: Add Jmx Testplan
      description: Have you added your JMX Testplan or a replica?
      options:
        - label: I have added my JMX Testplan in this issue
          required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Add Schema
      description: Have you added your schema or a replica to check it out?
      options:
        - label: I have added a schema in this issue
          required: true
  - type: input
    id: version
    attributes:
      label: KloadGen Version
      description: What version of KloadGen are you using?
      placeholder: ex. 3.5.2
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      value: ""
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell